<div class="container">
    <div class="row text-center mb-4">
        <h2 class="footer-logo text-black">Social Media</h2>
        <p class="mx-auto mt-4 fw-bolder">Encontre-me nas Redes Sociais!</p>
        <ul class="list-unstuled mt-4 social-icon">
            <li class="list-inline-item me-1"><a href="https://github.com/GuuhBoss" class="btn btn-outline-primary rounded-circle"><i class="fab fa-github" aria-hidden="true"></i></a></li>
            <li class="list-inline-item me-1"><a href="https://web.facebook.com/gustavinho.silva.10" class="btn btn-outline-primary rounded-circle"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
            <li class="list-inline-item me-1"><a href="https://www.instagram.com/guuhsiilvaaaaa/" class="btn btn-outline-primary rounded-circle"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
            <li class="list-inline-item me-1"><a href="https://www.linkedin.com/in/gustavosjob/" class="btn btn-outline-primary rounded-circle"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
            <!-- <li class="list-inline-item me-1"><a href="https://wa.me/351937115131?text=Olá! Sou Gustavo Silva, prazer!" class="btn btn-outline-primary rounded-circle"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li> -->
        </ul>
    </div>
</div>