<div class="position-absolute start-50 translate-middle" id="bread">
    <a class="navbar-brand" href="<?= $block->getUrl('/home') ?>">
        <img style="height: 75px" src="<?= $block->getViewFileUrl('img/Logo-Gustavinho2.png') ?>" alt="GSilva"/>
    </a>
    <div style=" --bs-breadcrumb-divider: url(&#34;data:image/svg + xml,%3Csvgxmlns='http://www.w3.org/2000/svg'width='8'height='8'%3E%3Cpathd='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z'fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb justify-content-center">
            <li class="breadcrumb-item"><a href="<?= $block->getUrl('/') ?>">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Blog</li>
        </ol>
    </div>
</div>