<div class="container-fluid">
     <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div
        class="collapse navbar-collapse justify-content-end"
        id="navbarSupportedContent"
    >
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="<?= $block->getUrl('/'); ?>">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?= $block->getUrl('blog'); ?>">BLOG</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?= $block->getUrl('contact'); ?>">CONTATO</a>
            </li>
        </ul>
        <ul class="navbar-nav d-none d-md-flex">
            <li class="nav-item ps-4"><a class="nav-link text-light" href="https://github.com/GuuhBoss" ><i class="fab fa-github" aria-hidden="true"></i></a></li>
            <li class="nav-item"><a class="nav-link text-light" href="https://web.facebook.com/gustavinho.silva.10"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
            <li class="nav-item"><a class="nav-link text-light" href="https://www.instagram.com/guuhsiilvaaaaa/"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
            <li class="nav-item"><a class="nav-link text-light" href="https://www.linkedin.com/in/gustavosjob/"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
            <!-- <li class="nav-item"><a class="nav-link text-light" href="https://wa.me/351937115131?text=Olá! Sou Gustavo Silva, prazer!"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li> -->
        </ul>
    </div>
</div>