<section class="container">
    <div class="d-flex row justify-items-evenly">
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 eng">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Piscina Oceânica</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="./blog/piscinaoceanica.html" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 eng">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Obra de 4 edificio, Enapor</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="./blog/obraportuaria.html" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 eng">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Reforma Casa de Banho</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="./blog/reformagarmaritimo.html" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 eng">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Gabinete Armazém</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="./blog/gabinetearmazem.html" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 dev">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Meu Quinto Post</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 eng">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Meu Sexto Post</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 dev">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Meu Sextimo Post</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 eng">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Meu Oitavo Post</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
        <div class="container-fluid col-lg-4 col-md-6 mt-4 py-2 px-5 dev">
            <div class="curva shadow overflow-hidden mb-3">
                <div class="row mb-4">
                    <img src="<?= $block->getViewFileUrl('img/const.jpg')?>" alt="" class="w-100 p-0" />
                </div>
                <div class="row mb-2 text-center"><h3>Meu Nono Post</h3></div>
                <div class="row mb-3 d-flex justify-content-evenly">
              <span class="col-5">
                <i class="fas fa-calendar-check" aria-hidden="true"></i>
                2021-08-18</span
              ><a href="" class="col-5"
                    >Saiba Mais <i class="fas fa-chevron-right"></i
                        ></a>
                </div>
            </div>
        </div>
    </div>
</section>