<section class="container">
    <div class="row text-center mt-5">
        <h2 class="text-black">Meu Curriculum Vitae</h2>
        <p class="mx-auto text-muted mt-4">
            Aqui estão alguns dos meus curriculos vitae.
        </p>
    </div>
    <div class="d-flex row justify-content-evenly">
        <div class="col-lg-4 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div class="curva overflow-hidden shadow-lg d-inline-block">
                        <img src="img/CV EC.jpeg" class="w-100" alt="" />
                        <span class="cert-badge badge bg-blue text-gold"
                        >Engenharia Civil</span
                        >
                    </div>
                    <a
                            href="./docs/Gustavo A. Rodrigues Silva - CV - EC.pdf "
                            download
                    >Baixe aqui o meu CV de Engenharia Civil
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div class="curva overflow-hidden shadow-lg d-inline-block">
                        <img src="img/CV TI.jpeg" class="w-100" alt="" />
                    </div>
                    <span class="cert-badge badge bg-blue text-gold"
                    >Web Developer</span
                    >
                    <a
                            href="./docs/Gustavo A. Rodrigues Silva - CV - CV - TI 3.pdf"
                            download
                    >Baixe aqui o meu CV de Web Developer
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="container">
    <div class="row text-center mt-5">
        <h2 class="text-black">Meus Certificados</h2>
        <p class="mx-auto text-muted mt-4">
            Aqui estão alguns dos meus certificados.
        </p>
    </div>
    <div class="d-flex row justify-content-evenly">
        <div class="col-lg-4 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div class="curva overflow-hidden shadow-lg d-inline-block">
                        <img
                                src="img/CertificadoEC.png"
                                class="w-100"
                                alt="Certificado de Conclusão em Engenharia Civil"
                        />
                    </div>
                    <span class="cert-badge badge bg-blue text-gold"
                    >Engenharia Civil</span
                    >
                    <a href="./docs/Certificado de Conclusão.pdf" download
                    >Baixe aqui o meu Certificado de Engenharia Civil
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div class="curva overflow-hidden shadow-lg d-inline-block">
                        <img
                                src="img/DiplomaDev.png"
                                class="w-100"
                                alt="Diploma Web Developer"
                        />
                    </div>
                    <span class="cert-badge badge bg-blue text-gold"
                    >Web Developer</span
                    >
                    <a href="./docs/Diploma Web Developer.pdf" download
                    >Baixe aqui o meu Diploma de Web Developer
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div class="curva overflow-hidden shadow-lg d-inline-block">
                        <img
                                src="img/DiplomaPython.png"
                                class="w-100"
                                alt="Diploma de Python Básico"
                        />
                    </div>
                    <span class="cert-badge badge bg-blue text-gold">Python</span>
                    <a href="./docs/Diploma Python.pdf" download
                    >Baixe aqui o meu Diploma de Python
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>