<div class="container mt-3">
    <div class="row _border">
        <div class="col d-flex justify-content-center border">
            <h1>Meu Currículo</h1>
        </div>
    </div>
    <div class="row _border">
        <div class="col d-flex justify-content-center border">
            <img src="img/gustavinho.jpg" width="175px" />
        </div>
        <div class="col-9 align-self-center border">
            <div class="d-flex justify-content-center">
                <h2>Gustavo de Alcântara Rodrigues da Silva</h2>
            </div>
            <div class="d-flex justify-content-center">
                <p>gustavosjob@gmail.com</p>
            </div>
        </div>
    </div>
    <hr />
    <div class="row _border">
        <h5 class="ps-5 ms-5"><u>EDUCAÇÃO</u></h5>
        <ul class="ps-4 ms-5">
            <li>
                Licenciatura em Engenharia Civil no Instituto Superior de Engenharia
                de Lisboa
            </li>
            <li>Curso Web Developer em Udemy</li>
        </ul>
    </div>
    <hr />
    <div class="row _border">
        <h5 class="ps-5 ms-5"><u>EXPERIÊNCIA EM TRABALHO PROFISSIONAL</u></h5>
        <br />
        <h5 class="ps-5 ms-5">BRICO DEPÔT - BRICOLAGE E CONSTRUÇÃO,</h5>
        <ul class="ps-4 ms-5">
            <li>Caixa, contato com o público</li>
            <li>
                Diversos conhecimentos em preços de materiais de construção e
                remodelações.
            </li>
        </ul>
    </div>
    <hr />
    <div class="row _border">
        <h5 class="ps-5 ms-5"><u>EXPERIÊNCIA EM TRABALHO VOLUNTÁRIO</u></h5>
        <br />
        <p class="ps-4 ms-5">
            <strong
            >Associação Brasileira Comunitária de Apoio a Família e ao Indivíduo
                - Cabo Verde Serviço Voluntário - 2 anos de experiência
            </strong>
        </p>
        <ul class="ps-4 ms-5">
            <li>
                Treinamento para mais de 7 colaboradores (18 – 26 anos de idade);
            </li>
            <li>Ajuda na adaptação e qualificação dos novos colaboradores;</li>
            <li>Abordagem a pessoas de diferentes classes sociais;</li>
            <li>Estabelecimento de metas acompanhamentos de resultados;</li>
            <li>Organizar e preparar eventos;</li>
        </ul>
    </div>
    <hr />
    <div class="row _border">
        <div class="col-6 border-end">
            <h5 class="ps-5 ms-5"><u>COMPENTÊNCIAS DE LÍNGUA</u></h5>
            <ul class="ps-4 ms-5">
                <li>Português – Falante Nativo</li>
                <li>Inglês – C1 (Avançado)</li>
                <li>Espanhol – B1 (Intermedio)</li>
            </ul>
        </div>
        <div class="col-6">
            <h5 class="ps-5 ms-5"><u>COMPENTÊNCIAS DE SOFTWARE</u></h5>
            <ul>
                <li>
                    Word Office, PowerPoint Office, Excel Office,
                    <strong> Project MS </strong>
                </li>
                <li>Engenharia (AutoCAD, Civil 3D, Ftools, SAP 2000)</li>
                <li>Tecnologia (Python, JavaScript, PHP, MySQL ,..)</li>
            </ul>
        </div>
    </div>
    <hr />
    <div class="row _border">
        <h5 class="ps-5 ms-5"><u> OUTRAS COMPENTÊNCIAS</u></h5>
        <ul class="ps-4 ms-5">
            <li>Carta de Condução</li>
            <li>Boa comunicação com chefes e colegas de equipa</li>
            <li>Aprendizagem Rápida</li>
            <li>Mantém confidencialidade, confiança e integridade pessoal</li>
            <li>Disponível para trabalhar com vigilância mínima</li>
            <li>Habilidade para gerir projetos quando requerido</li>
            <li>Responsável</li>
        </ul>
    </div>
    <hr />
    <div class="row _border">
        <div class="col-4">
            <img src="" width="35" /> +351 93 711 51 31
            <br />
            <img src="" width="35" /> @guuhsiilva
        </div>
        <div class="col-4">
            <img src="" width="35" /> (Cabo Verde) +238 976 61 63
            <br />
            <img src="" width="35" /> (Portugal) +351 21 988 75 34
        </div>
    </div>
</div>