<section class="container">
    <div class="row text-center mt-5">
        <h2 class="text-black">Experiência de Trabalho</h2>
        <p class="mx-auto text-muted mt-4">
            Durante minha carreira e até mesmo no meu tempo livre trabalhei com
            vários softwares! Aqui vai uma lista de alguns que eu me sinto mais
            confortável.
        </p>
    </div>
    <div class="d-flex row justify-content-evenly">
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/revit.png" width="100" height="100" alt="Revit" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Revit</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/autocad.png"
                            width="100"
                            height="100"
                            alt="AutoCAD"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">AutoCAD</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/cype.png"
                            width="100"
                            height="100"
                            alt="CypeCAD"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">CypeCAD</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/robot.png" width="100" height="100" alt="Robot" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Robot</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/civil3d.png"
                            width="100"
                            height="100"
                            alt="Civil3D"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Civil3D</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/msproject.png"
                            width="100"
                            height="100"
                            alt="MS Project"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold"
                    >MS Project</span
                    >
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/excel.png" width="100" height="100" alt="Excel" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Excel</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/php.png" width="100" height="100" alt="PHP" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">PHP</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/python.png"
                            width="100"
                            height="100"
                            alt="Python"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Python</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/javascript.png"
                            width="100"
                            height="100"
                            alt="JavaScript"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold"
                    >HTML, CSS, JS</span
                    >
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/react.png" width="100" height="100" alt="React" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">React</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/mysql.png"
                            width="100"
                            height="100"
                            alt="Maria DB"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">MySQL</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img
                            src="img/laravel.png"
                            width="100"
                            height="100"
                            alt="Laravel"
                        />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Laravel</span>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="container">
    <div class="row text-center mt-5">
        <h2 class="text-black">Planos Futuros</h2>
        <p class="mx-auto text-muted mt-4">
            E claro tenho planos para continuar a progredir! Dê uma olhada quais
            os proximos planos que tenho desejo de aprender.
        </p>
    </div>
    <div class="d-flex row justify-content-evenly">
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/naviswork.png" width="100" height="100" alt="" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Naviswork</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/java.png" width="100" height="100" alt="" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">Java</span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mt-4 py-2 px-5">
            <div class="card border-0 text-center bg-white p-3">
                <div class="card-body p-0">
                    <div
                        class="rounded-circle overflow-hidden shadow-lg d-inline-block"
                    >
                        <img src="img/mongodb.png" width="100" height="100" alt="" />
                    </div>
                    <span class="skill-badge badge bg-blue text-gold">MongoDB</span>
                </div>
            </div>
        </div>
    </div>
</section>