<section class="mt-4">
    <div class="container">
        <div class="row text-center borda-start">
            <h2 class="text-black">Experiências Profissionais</h2>
        </div>
        <div class="row pt-4 borda-start borda-bottom position-relative">
            <span class="esq">4</span>
            <div class="col offset-sm-2">
                <h5>ENAPOR - AUTORIDADE PORTUÁRIA DE CABO VERDE</h5>
                <h6 class="text-muted ms-3"><i>ABR 2021 - DEZ 2021</i></h6>
                <ul class="timeline">
                    <li>
                        Supervisiono e acompanho alguns de trabalhos de construção
                    </li>
                    <li>
                        Crio alguns de orçamentos para manutenção em várias áreas da
                        própria empresa
                    </li>
                    <li>
                        Crio vários projetos de construção civil em 3D com Revit (BIM),
                        e também levantamento de plantas de alguns edifícios existentes
                        onde já havia ocorrido alguma modelação cuja a planta estava
                        desatualizada
                    </li>
                    <li>
                        Faço a gestão de vários contratos com os empreiteiros e
                        consultores
                    </li>
                    <li>
                        Participo em reuniões com os empreiteiros semanalmente e
                        acompanho os seus trabalhos
                    </li>
                    <li>Faço as tarefas normalmente muito rápidas e com qualidade</li>
                    <li>
                        Como engenheiro civil, estou familiarizado com os projetos
                        arquitetónicos, estruturais, de saneamento e elétricos
                    </li>
                </ul>
            </div>
        </div>
        <div class="row pt-4 borda-end borda-bottom position-relative">
            <span class="dir">3</span>
            <div class="col offset-sm-2">
                <h5>FERBROCA - ARMAZÉNISTA DE FERRAMENTAS</h5>
                <h6 class="text-muted ms-3"><i>AGO 2019 - SET 2019</i></h6>
                <ul class="timeline">
                    <li>Condução de uma empilhadora</li>
                    <li>Melhorei o espaço de trabalho</li>
                    <li>
                        Assegurei que o local se mantinha limpo para evitar acidentes
                    </li>
                    <li>Trabalhei com altos pesos</li>
                </ul>
            </div>
        </div>
        <div class="row pt-4 borda-start borda-bottom position-relative">
            <span class="esq">2</span>
            <div class="col offset-sm-2">
                <h5>BRICO DEPÔT - BRICOLAGE & CONSTRUÇÃO</h5>
                <h6 class="text-muted ms-3"><i>SET 2018 - NOV 2018</i></h6>
                <ul class="timeline">
                    <li>Contactei com o público</li>
                    <li>Fui um contador de dinheiro altamente confiável</li>
                    <li>Aprendi bastante sobre preços de diversos matériais</li>
                    <li>Lidei com trabalhos sobre pressão</li>
                </ul>
            </div>
        </div>
        <div class="row text-center pt-4 borda-end">
            <h2 class="text-black">Experiências Voluntárias</h2>
        </div>
        <div class="row pt-4 borda-end position-relative">
            <span class="dir">1</span>
            <div class="col offset-sm-2">
                <h5>Serviço Voluntário Mundial | Missão Cabo Verde Praia</h5>
                <h6 class="text-muted ms-3"><i>SET 2015 - SET 2017</i></h6>
                <ul class="timeline">
                    <li>Dei treinamentos para mais de 18 jovens</li>
                    <li>Ajudei novos colegas a se adaptarem ao meio</li>
                    <li>Abordei várias pessoas de diferentes classes sociais</li>
                    <li>Criação de metas e acompanhamento dos resultados</li>
                    <li>Organizei e preparei eventos</li>
                </ul>
            </div>
        </div>
    </div>
</section>